<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [1]:
import sys

sys.path.append("/home/matthias/git/background_foreground_segmentation/src/")
print(sys.path)

['/home/matthias/git/background_foreground_segmentation', '/home/matthias/anaconda3/envs/bfs1/lib/python36.zip', '/home/matthias/anaconda3/envs/bfs1/lib/python3.6', '/home/matthias/anaconda3/envs/bfs1/lib/python3.6/lib-dynload', '', '/home/matthias/anaconda3/envs/bfs1/lib/python3.6/site-packages', '/home/matthias/anaconda3/envs/bfs1/lib/python3.6/site-packages/IPython/extensions', '/home/matthias/.ipython', '/home/matthias/git/background_foreground_segmentation/src/']


In [2]:
import tensorflow as tf
import tensorflow_addons as tfa
import tensorflow_datasets as tfds
from zipfile import ZipFile
import os


import bfseg.models.fast_scnn
import bfseg.data.hive.office_rumlang_validation_labeled
import bfseg.data.hive.bfseg_validation_labeled
from bfseg.utils.utils import load_gdrive_file
#from bfseg.settings import TMPDIR
TMPDIR = "/home/matthias/data/rss_2021_data/tmp/"

ModuleNotFoundError: No module named 'bfseg.models'

In [5]:
# MY VERSION: load the  model from gdrive 
tf.keras.models.load_model('/home/matthias/data/rss_2021_data/xavier_models/model_epoch_final_rumlang1_test.h5')

/home/matthias/anaconda3/envs/bfs1/lib/python3.6/site-packages/tensorflow/python/keras/layers/core.py:1045: UserWarning: bfseg.models.fast_scnn is not loaded, but a Lambda layer uses it. It may cause errors.
  , UserWarning)


NameError: name 'tf' is not defined

In [9]:
# load the  model from gdrive
ZipFile(load_gdrive_file('1ZF2nYMD9PE0kr435TrDVLpaHuDUBSOC5',
                        ending='zip')).extractall(
                            os.path.join(TMPDIR, 'segmentation_model'))
model = tf.saved_model.load(os.path.join(TMPDIR, 'segmentation_model'))



In [20]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('bfseg_validation_labeled', split='CLA').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()


<tf.Tensor: shape=(), dtype=float32, numpy=0.40327787>

In [11]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('office_rumlang_validation_labeled', split='RUMLANG').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.2940687>

In [22]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('office_rumlang_validation_labeled', split='RUMLANG').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.29405522>