<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"></ul></div>

In [9]:
import tensorflow as tf
import tensorflow_addons as tfa
import tensorflow_datasets as tfds
from zipfile import ZipFile


import bfseg.data.hive.office_rumlang_validation_labeled
import bfseg.data.hive.bfseg_validation_labeled
from bfseg.utils.utils import load_gdrive_file
from bfseg.settings import TMPDIR


In [17]:
# load the  model
ZipFile(load_gdrive_file('1ZF2nYMD9PE0kr435TrDVLpaHuDUBSOC5',
                        ending='zip')).extractall(
                            os.path.join(TMPDIR, 'segmentation_model'))
model = tf.saved_model.load(os.path.join(TMPDIR, 'segmentation_model'))



In [20]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('bfseg_validation_labeled', split='CLA').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()


<tf.Tensor: shape=(), dtype=float32, numpy=0.40327787>

In [21]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('office_rumlang_validation_labeled', split='OFFICE').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()

Dl Completed...: 0 url [00:00, ? url/s]

Dl Size...: 0 MiB [00:00, ? MiB/s]

Generating splits...:   0%|          | 0/2 [00:00<?, ? splits/s]

Generating OFFICE examples...: 0 examples [00:00, ? examples/s]

Shuffling office_rumlang_validation_labeled-OFFICE.tfrecord...:   0%|          | 0/31 [00:00<?, ? examples/s]

Generating RUMLANG examples...: 0 examples [00:00, ? examples/s]

Shuffling office_rumlang_validation_labeled-RUMLANG.tfrecord...:   0%|          | 0/26 [00:00<?, ? examples/s]

Dataset office_rumlang_validation_labeled downloaded and prepared to /home/blumh/tensorflow_datasets/office_rumlang_validation_labeled/1.0.0. Subsequent calls will reuse this data.


<tf.Tensor: shape=(), dtype=float32, numpy=0.46286935>

In [22]:
miou = tf.keras.metrics.MeanIoU(num_classes=2)
for batch in tfds.load('office_rumlang_validation_labeled', split='RUMLANG').batch(1):
    pred = tf.argmax(model(
        tf.image.convert_image_dtype(batch['image'], tf.float32)),
        axis=-1)
    miou.update_state(batch['label'], pred)
miou.result()

<tf.Tensor: shape=(), dtype=float32, numpy=0.29405522>